[scan]
exclude_dirs = ["node_modules", ".vscode", ".idea", ".angular", "build", "backend", "docs", ".git", "src-tauri", "images", "dist", "target"]
include_extensions = ["html", "js", "jsx", "ts", "tsx", "php", "rs"]
css_extensions = ["css", "scss"]
