[scan]
exclude_dirs = ["node_modules", "dist", ".vscode", ".idea", ".angular", "build", "target", "backend", "docs", ".git"]
include_extensions = ["html", "js", "jsx", "ts", "tsx", "php"]
css_extensions = ["css", "scss"]
